export const StudendSampleData =
[
    {
      "_id":10,
       "FirstName":"Ram",
       "LastName":"",
       "Department":"IT",
       "Year":"2022",
       "StudnetRollNo":"std000100"
    },
    {
      "_id":11,
       "FirstName":"Anu",
       "LastName":"",
       "Department":"IT",
       "Year":"2022",
       "StudnetRollNo":"std000101"
    },
    {
      "_id":12,
       "FirstName":"Abu",
       "LastName":"",
       "Department":"IT",
       "Year":"2022",
       "StudnetRollNo":"std000102"
    },
    {
      "_id":13,
       "FirstName":"Binu",
       "LastName":"",
       "Department":"IT",
       "Year":"2022",
       "StudnetRollNo":"std000103"
    },
    {
      "_id":14,
       "FirstName":"Mathew",
       "LastName":"",
       "Department":"CSE",
       "Year":"2022",
       "StudnetRollNo":"std000104"
    },
    {
      "_id":15,
       "FirstName":"Nazir",
       "LastName":"",
       "Department":"CSE",
       "Year":"2022",
       "StudnetRollNo":"std000105"
    },
    {
      "_id":16,
       "FirstName":"Suresh",
       "LastName":"",
       "Department":"CSE",
       "Year":"2022",
       "StudnetRollNo":"std000106"
    },
    {
      "_id":17,
       "FirstName":"Pravin",
       "LastName":"",
       "Department":"CSE",
       "Year":"2022",
       "StudnetRollNo":"std000107"
    },
    {
      "_id":18,
       "FirstName":"Harish",
       "LastName":"",
       "Department":"BCA",
       "Year":"2022",
       "StudnetRollNo":"std000108"
    },
    {
      "_id":19,
       "FirstName":"Vijay",
       "LastName":"",
       "Department":"BCA",
       "Year":"2022",
       "StudnetRollNo":"std000109"
    },
    {
      "_id":20,
       "FirstName":"Hari",
       "LastName":"",
       "Department":"BCA",
       "Year":"2022",
       "StudnetRollNo":"std000110"
    },
    {
      "_id":21,
       "FirstName":"Daniel",
       "LastName":"",
       "Department":"BCA",
       "Year":"2022",
       "StudnetRollNo":"std000111"
    }
 ]
 